// SPDX-FileCopyrightText: (C) 2024 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	networkv1alpha1 "github.com/open-edge-platform/app-orch-deployment/app-interconnect/pkg/apis/network/v1alpha1"
	versioned "github.com/open-edge-platform/app-orch-deployment/app-interconnect/pkg/clientset/versioned"
	internalinterfaces "github.com/open-edge-platform/app-orch-deployment/app-interconnect/pkg/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/open-edge-platform/app-orch-deployment/app-interconnect/pkg/listers/network/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkClusterInformer provides access to a shared informer and lister for
// NetworkClusters.
type NetworkClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NetworkClusterLister
}

type networkClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNetworkClusterInformer constructs a new informer for NetworkCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetworkClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetworkClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNetworkClusterInformer constructs a new informer for NetworkCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetworkClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkV1alpha1().NetworkClusters().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NetworkV1alpha1().NetworkClusters().Watch(context.TODO(), options)
			},
		},
		&networkv1alpha1.NetworkCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *networkClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetworkClusterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *networkClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&networkv1alpha1.NetworkCluster{}, f.defaultInformer)
}

func (f *networkClusterInformer) Lister() v1alpha1.NetworkClusterLister {
	return v1alpha1.NewNetworkClusterLister(f.Informer().GetIndexer())
}
