# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = [
    "venv_app-service-proxy/**", "out/*", "**go.sum", ".tool-versions", "**.json", "VERSION", "api/buf.lock",
    "pkg/api/**.pb**.go", "api/spec/**", "api/nbi/v2/pkg/restClient/**", "artifacts/**", "internal/southbound/mocks/**",
    "artifacts/**", "BDBA/**", "internal/kubernetes/mocks/**", "internal/kubevirt/mocks/**", "internal/wsproxy/mocks/**",
    "internal/adm/mocks/**", "api/nbi/v2/spec/**", "api/nbi/v2/resource/v2/**", "PROJECT", ".htmllintrc",
    "web-login/*.js", "bin/**", "build/_output/**", "app-service-proxy"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["config/**", "README.md", "venv_app-service-proxy/**"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
