# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    {{- include "app-service-proxy-agent.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-service-controller
