// SPDX-FileCopyrightText: (C) 2024 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkClusterListerExpansion allows custom methods to be added to
// NetworkClusterLister.
type NetworkClusterListerExpansion interface{}

// NetworkLinkListerExpansion allows custom methods to be added to
// NetworkLinkLister.
type NetworkLinkListerExpansion interface{}

// NetworkServiceListerExpansion allows custom methods to be added to
// NetworkServiceLister.
type NetworkServiceListerExpansion interface{}
