# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment CustomResourceDefinitions
name: app-deployment-crd
# Correct version will be added by "make helm-package" from VERSION
version: 2.7.1
annotations:
  revision: "d2f3a5b"
  created: "2026-04-01T14:29:18Z"
appVersion: 2.7.1
