# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment CustomResourceDefinitions
name: app-deployment-crd
# Correct version will be added by "make helm-package" from VERSION
version: 2.6.2-dev
annotations:
  revision: "248e56d"
  created: "2026-03-02T07:21:43Z"
appVersion: 2.6.2-dev-248e56d
