openapi: 3.1.0
info:
  title: resource.v2
paths:
  /resource.orchestrator.apis/v2/workloads/pods/{cluster_id}/{namespace}/{pod_name}/delete:
    put:
      tags:
        - resource.v2.PodService
      summary: DeletePod
      description: Deletes the pod for an application in a cluster.
      operationId: resource.v2.PodService.DeletePod
      parameters:
        - name: cluster_id
          in: path
          description: Cluster ID
          required: true
          schema:
            type: string
            title: cluster_id
            maxLength: 40
            minLength: 1
            pattern: ^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$
            description: Cluster ID
        - name: namespace
          in: path
          description: Namespace that the pod is running on.
          required: true
          schema:
            type: string
            title: namespace
            maxLength: 253
            minLength: 1
            pattern: ^[a-z0-9]([-a-z0-9-]*[a-z0-9])?$
            description: Namespace that the pod is running on.
        - name: pod_name
          in: path
          description: Name of the pod.
          required: true
          schema:
            type: string
            title: pod_name
            maxLength: 253
            minLength: 1
            pattern: ^[a-z0-9]([-a-z0-9-]*[a-z0-9])?$
            description: Name of the pod.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resource.v2.DeletePodResponse'
components:
  schemas:
    resource.v2.DeletePodRequest:
      type: object
      properties:
        clusterId:
          type: string
          title: cluster_id
          maxLength: 40
          minLength: 1
          pattern: ^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$
          description: Cluster ID
        namespace:
          type: string
          title: namespace
          maxLength: 253
          minLength: 1
          pattern: ^[a-z0-9]([-a-z0-9-]*[a-z0-9])?$
          description: Namespace that the pod is running on.
        podName:
          type: string
          title: pod_name
          maxLength: 253
          minLength: 1
          pattern: ^[a-z0-9]([-a-z0-9-]*[a-z0-9])?$
          description: Name of the pod.
      title: DeletePodRequest
      required:
        - clusterId
        - namespace
        - podName
      additionalProperties: false
      description: Request message for DeletePod method
    resource.v2.DeletePodResponse:
      type: object
      title: DeletePodResponse
      additionalProperties: false
      description: Response message for the DeletePod method.
security: []
tags:
  - name: resource.v2.PodService
    description: Provides API to manage a pod workload such as deleting a pod.
