# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
data:
  values: IyBTUERYLUZpbGVDb3B5cmlnaHRUZXh0OiAoQykgMjAyMyBJbnRlbCBDb3Jwb3JhdGlvbgojIFNQRFgtTGljZW5zZS1JZGVudGlmaWVyOiBMaWNlbnNlUmVmLUludGVsCi0tLQptYXJpYWRiOgogIHByaW1hcnk6CiAgICBwZXJzaXN0ZW5jZToKICAgICAgZW5hYmxlZDogZmFsc2UKICBhdXRoOgogICAgcGFzc3dvcmQ6IHBhc3N3b3JkCiAgICByb290UGFzc3dvcmQ6IHNlY3JldHBhc3N3b3JkCndvcmRwcmVzc1VzZXJuYW1lOiBhZG1pbgp3b3JkcHJlc3NQYXNzd29yZDogcGFzc3dvcmQKcGVyc2lzdGVuY2U6CiAgZW5hYmxlZDogZmFsc2UK
kind: Secret
metadata:
  name: wordpress-0.1.0-profile
  namespace: clusters
type: Opaque
---
apiVersion: app.edge-orchestrator.intel.com/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: wordpress-example
    app.kubernetes.io/part-of: app-deployment-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app-deployment-manager
  name: wordpress-example
  namespace: clusters
spec:
  displayName: "My Wordpress Blog"
  project: test-project
  deploymentType: auto-scaling
  applications:
    - name: wordpress
      version: 0.1.0
      namespace: apps0
      targets:
        color: blue
      helmApp:
        chart: wordpress
        version: 15.2.42
        repo: https://charts.bitnami.com/bitnami
      profileSecretName: wordpress-0.1.0-profile
  deploymentPackageRef:
    publisher: intel
    name: wordpress
    version: 0.1.0
    profileName: default
