{
 "title": "Time_measurement_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average_deploy_to_running_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(time_difference_between_events{lastEvent=\"status-change\", lastPart=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DeploymentCluster_To_Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(displayName) (time_difference_between_events{lastPart=\"Running\", lastEvent!=\"status-change\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deploy_to_Running_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time_difference_between_events{lastEvent=\"status-change\", lastPart=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}