// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: resource/v2/app_workload_resource.proto

package resourcev2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _app_workload_resource_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AppWorkload with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AppWorkload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AppWorkload with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AppWorkloadMultiError, or
// nil if none found.
func (m *AppWorkload) ValidateAll() error {
	return m.validate(true)
}

func (m *AppWorkload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if err := m._validateUuid(m.GetId()); err != nil {
		err = AppWorkloadValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 253 {
		err := AppWorkloadValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 253 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_AppWorkload_Name_Pattern.MatchString(m.GetName()) {
		err := AppWorkloadValidationError{
			field:  "Name",
			reason: "value does not match regex pattern \"^[a-z0-9]([-a-z0-9-]*[a-z0-9])?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Namespace

	if all {
		switch v := interface{}(m.GetCreateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AppWorkloadValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AppWorkloadValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AppWorkloadValidationError{
				field:  "CreateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for WorkloadReady

	switch v := m.Workload.(type) {
	case *AppWorkload_VirtualMachine:
		if v == nil {
			err := AppWorkloadValidationError{
				field:  "Workload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetVirtualMachine()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AppWorkloadValidationError{
						field:  "VirtualMachine",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AppWorkloadValidationError{
						field:  "VirtualMachine",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetVirtualMachine()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AppWorkloadValidationError{
					field:  "VirtualMachine",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AppWorkload_Pod:
		if v == nil {
			err := AppWorkloadValidationError{
				field:  "Workload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetPod()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AppWorkloadValidationError{
						field:  "Pod",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AppWorkloadValidationError{
						field:  "Pod",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPod()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AppWorkloadValidationError{
					field:  "Pod",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return AppWorkloadMultiError(errors)
	}

	return nil
}

func (m *AppWorkload) _validateUuid(uuid string) error {
	if matched := _app_workload_resource_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AppWorkloadMultiError is an error wrapping multiple validation errors
// returned by AppWorkload.ValidateAll() if the designated constraints aren't met.
type AppWorkloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AppWorkloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AppWorkloadMultiError) AllErrors() []error { return m }

// AppWorkloadValidationError is the validation error returned by
// AppWorkload.Validate if the designated constraints aren't met.
type AppWorkloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AppWorkloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AppWorkloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AppWorkloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AppWorkloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AppWorkloadValidationError) ErrorName() string { return "AppWorkloadValidationError" }

// Error satisfies the builtin error interface
func (e AppWorkloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAppWorkload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AppWorkloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AppWorkloadValidationError{}

var _AppWorkload_Name_Pattern = regexp.MustCompile("^[a-z0-9]([-a-z0-9-]*[a-z0-9])?$")
