// SPDX-FileCopyrightText: (C) 2023 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: resource/v2/endpoint_service.proto

package resourcev2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for ListAppEndpoints method
type ListAppEndpointsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Cluster ID
	ClusterId     string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppEndpointsRequest) Reset() {
	*x = ListAppEndpointsRequest{}
	mi := &file_resource_v2_endpoint_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppEndpointsRequest) ProtoMessage() {}

func (x *ListAppEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_endpoint_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListAppEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_resource_v2_endpoint_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAppEndpointsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListAppEndpointsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// Response message for the ListAppEndpoints method.
type ListAppEndpointsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of services.
	AppEndpoints  []*AppEndpoint `protobuf:"bytes,1,rep,name=app_endpoints,json=appEndpoints,proto3" json:"app_endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppEndpointsResponse) Reset() {
	*x = ListAppEndpointsResponse{}
	mi := &file_resource_v2_endpoint_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppEndpointsResponse) ProtoMessage() {}

func (x *ListAppEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_endpoint_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListAppEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_resource_v2_endpoint_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAppEndpointsResponse) GetAppEndpoints() []*AppEndpoint {
	if x != nil {
		return x.AppEndpoints
	}
	return nil
}

var File_resource_v2_endpoint_service_proto protoreflect.FileDescriptor

const file_resource_v2_endpoint_service_proto_rawDesc = "" +
	"\n" +
	"\"resource/v2/endpoint_service.proto\x12\vresource.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a#resource/v2/endpoint_resource.proto\x1a\x17validate/validate.proto\"\xbb\x01\n" +
	"\x17ListAppEndpointsRequest\x12K\n" +
	"\x06app_id\x18\x01 \x01(\tB4\xe0A\x02\xfaB.r,\x10\x01\x18P2&^[a-z0-9][a-z0-9-]{0,78}[a-z0-9]{0,1}$R\x05appId\x12S\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB4\xe0A\x02\xfaB.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\tclusterId\"f\n" +
	"\x18ListAppEndpointsResponse\x12J\n" +
	"\rapp_endpoints\x18\x01 \x03(\v2\x18.resource.v2.AppEndpointB\v\xe0A\x03\xfaB\x05\x92\x01\x02\x10dR\fappEndpoints2\xbc\x01\n" +
	"\x10EndpointsService\x12\xa7\x01\n" +
	"\x10ListAppEndpoints\x12$.resource.v2.ListAppEndpointsRequest\x1a%.resource.v2.ListAppEndpointsResponse\"F\x82\xd3\xe4\x93\x02@\x12>/resource.orchestrator.apis/v2/endpoints/{app_id}/{cluster_id}B\xde\x01\n" +
	"\x0fcom.resource.v2B\x14EndpointServiceProtoP\x01Zhgithub.com/open-edge-platform/app-orch-deployment/app-resource-manager/api/nbi/v2/resource/v2;resourcev2\xa2\x02\x03RXX\xaa\x02\vResource.V2\xca\x02\vResource\\V2\xe2\x02\x17Resource\\V2\\GPBMetadata\xea\x02\fResource::V2b\x06proto3"

var (
	file_resource_v2_endpoint_service_proto_rawDescOnce sync.Once
	file_resource_v2_endpoint_service_proto_rawDescData []byte
)

func file_resource_v2_endpoint_service_proto_rawDescGZIP() []byte {
	file_resource_v2_endpoint_service_proto_rawDescOnce.Do(func() {
		file_resource_v2_endpoint_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v2_endpoint_service_proto_rawDesc), len(file_resource_v2_endpoint_service_proto_rawDesc)))
	})
	return file_resource_v2_endpoint_service_proto_rawDescData
}

var file_resource_v2_endpoint_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_v2_endpoint_service_proto_goTypes = []any{
	(*ListAppEndpointsRequest)(nil),  // 0: resource.v2.ListAppEndpointsRequest
	(*ListAppEndpointsResponse)(nil), // 1: resource.v2.ListAppEndpointsResponse
	(*AppEndpoint)(nil),              // 2: resource.v2.AppEndpoint
}
var file_resource_v2_endpoint_service_proto_depIdxs = []int32{
	2, // 0: resource.v2.ListAppEndpointsResponse.app_endpoints:type_name -> resource.v2.AppEndpoint
	0, // 1: resource.v2.EndpointsService.ListAppEndpoints:input_type -> resource.v2.ListAppEndpointsRequest
	1, // 2: resource.v2.EndpointsService.ListAppEndpoints:output_type -> resource.v2.ListAppEndpointsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_v2_endpoint_service_proto_init() }
func file_resource_v2_endpoint_service_proto_init() {
	if File_resource_v2_endpoint_service_proto != nil {
		return
	}
	file_resource_v2_endpoint_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v2_endpoint_service_proto_rawDesc), len(file_resource_v2_endpoint_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_v2_endpoint_service_proto_goTypes,
		DependencyIndexes: file_resource_v2_endpoint_service_proto_depIdxs,
		MessageInfos:      file_resource_v2_endpoint_service_proto_msgTypes,
	}.Build()
	File_resource_v2_endpoint_service_proto = out.File
	file_resource_v2_endpoint_service_proto_goTypes = nil
	file_resource_v2_endpoint_service_proto_depIdxs = nil
}
