// SPDX-FileCopyrightText: (C) 2023 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: resource/v2/endpoint_resource.proto

package resourcev2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointStatus_State int32

const (
	EndpointStatus_STATE_UNSPECIFIED EndpointStatus_State = 0
	EndpointStatus_STATE_READY       EndpointStatus_State = 1
	EndpointStatus_STATE_NOT_READY   EndpointStatus_State = 2
)

// Enum value maps for EndpointStatus_State.
var (
	EndpointStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_READY",
		2: "STATE_NOT_READY",
	}
	EndpointStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_READY":       1,
		"STATE_NOT_READY":   2,
	}
)

func (x EndpointStatus_State) Enum() *EndpointStatus_State {
	p := new(EndpointStatus_State)
	*p = x
	return p
}

func (x EndpointStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_v2_endpoint_resource_proto_enumTypes[0].Descriptor()
}

func (EndpointStatus_State) Type() protoreflect.EnumType {
	return &file_resource_v2_endpoint_resource_proto_enumTypes[0]
}

func (x EndpointStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointStatus_State.Descriptor instead.
func (EndpointStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_resource_v2_endpoint_resource_proto_rawDescGZIP(), []int{3, 0}
}

// Represents an endpoint for accessing the application outside of a cluster.
type AppEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint object UID (e.g. service or ingress UID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Endpoint name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Fully qualified domain name (FQDN) for external access.
	Fqdns []*Fqdn `protobuf:"bytes,5,rep,name=fqdns,proto3" json:"fqdns,omitempty"`
	// List of ports exposed by a service for external access
	Ports []*Port `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	// EndpointStatus status of an endpoint
	EndpointStatus *EndpointStatus `protobuf:"bytes,7,opt,name=endpoint_status,json=endpointStatus,proto3" json:"endpoint_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppEndpoint) Reset() {
	*x = AppEndpoint{}
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppEndpoint) ProtoMessage() {}

func (x *AppEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppEndpoint.ProtoReflect.Descriptor instead.
func (*AppEndpoint) Descriptor() ([]byte, []int) {
	return file_resource_v2_endpoint_resource_proto_rawDescGZIP(), []int{0}
}

func (x *AppEndpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppEndpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppEndpoint) GetFqdns() []*Fqdn {
	if x != nil {
		return x.Fqdns
	}
	return nil
}

func (x *AppEndpoint) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *AppEndpoint) GetEndpointStatus() *EndpointStatus {
	if x != nil {
		return x.EndpointStatus
	}
	return nil
}

// Fully qualified domain name.
type Fqdn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqdn          string                 `protobuf:"bytes,5,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fqdn) Reset() {
	*x = Fqdn{}
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fqdn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fqdn) ProtoMessage() {}

func (x *Fqdn) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fqdn.ProtoReflect.Descriptor instead.
func (*Fqdn) Descriptor() ([]byte, []int) {
	return file_resource_v2_endpoint_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Fqdn) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

// Port information
type Port struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Port name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Port value
	Value int32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	// Protocol for a port.
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Service proxy URL for a port.
	ServiceProxyUrl string `protobuf:"bytes,4,opt,name=service_proxy_url,json=serviceProxyUrl,proto3" json:"service_proxy_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_resource_v2_endpoint_resource_proto_rawDescGZIP(), []int{2}
}

func (x *Port) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Port) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Port) GetServiceProxyUrl() string {
	if x != nil {
		return x.ServiceProxyUrl
	}
	return ""
}

// Status of the endpoint.
type EndpointStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint state, either Ready or NotReady.
	State         EndpointStatus_State `protobuf:"varint,1,opt,name=state,proto3,enum=resource.v2.EndpointStatus_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointStatus) Reset() {
	*x = EndpointStatus{}
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointStatus) ProtoMessage() {}

func (x *EndpointStatus) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_endpoint_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointStatus.ProtoReflect.Descriptor instead.
func (*EndpointStatus) Descriptor() ([]byte, []int) {
	return file_resource_v2_endpoint_resource_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointStatus) GetState() EndpointStatus_State {
	if x != nil {
		return x.State
	}
	return EndpointStatus_STATE_UNSPECIFIED
}

var File_resource_v2_endpoint_resource_proto protoreflect.FileDescriptor

const file_resource_v2_endpoint_resource_proto_rawDesc = "" +
	"\n" +
	"#resource/v2/endpoint_resource.proto\x12\vresource.v2\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17validate/validate.proto\"\x9b\x02\n" +
	"\vAppEndpoint\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x03\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12H\n" +
	"\x04name\x18\x02 \x01(\tB4\xe0A\x03\xfaB.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\x04name\x12,\n" +
	"\x05fqdns\x18\x05 \x03(\v2\x11.resource.v2.FqdnB\x03\xe0A\x03R\x05fqdns\x12,\n" +
	"\x05ports\x18\x06 \x03(\v2\x11.resource.v2.PortB\x03\xe0A\x03R\x05ports\x12I\n" +
	"\x0fendpoint_status\x18\a \x01(\v2\x1b.resource.v2.EndpointStatusB\x03\xe0A\x03R\x0eendpointStatus\"#\n" +
	"\x04Fqdn\x12\x1b\n" +
	"\x04fqdn\x18\x05 \x01(\tB\a\xfaB\x04r\x02h\x01R\x04fqdn\"\xbd\x01\n" +
	"\x04Port\x12H\n" +
	"\x04name\x18\x01 \x01(\tB4\xe0A\x03\xfaB.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\x04name\x12\x19\n" +
	"\x05value\x18\x02 \x01(\x05B\x03\xe0A\x03R\x05value\x12\x1f\n" +
	"\bprotocol\x18\x03 \x01(\tB\x03\xe0A\x03R\bprotocol\x12/\n" +
	"\x11service_proxy_url\x18\x04 \x01(\tB\x03\xe0A\x03R\x0fserviceProxyUrl\"\x94\x01\n" +
	"\x0eEndpointStatus\x12<\n" +
	"\x05state\x18\x01 \x01(\x0e2!.resource.v2.EndpointStatus.StateB\x03\xe0A\x03R\x05state\"D\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATE_READY\x10\x01\x12\x13\n" +
	"\x0fSTATE_NOT_READY\x10\x02B\xdf\x01\n" +
	"\x0fcom.resource.v2B\x15EndpointResourceProtoP\x01Zhgithub.com/open-edge-platform/app-orch-deployment/app-resource-manager/api/nbi/v2/resource/v2;resourcev2\xa2\x02\x03RXX\xaa\x02\vResource.V2\xca\x02\vResource\\V2\xe2\x02\x17Resource\\V2\\GPBMetadata\xea\x02\fResource::V2b\x06proto3"

var (
	file_resource_v2_endpoint_resource_proto_rawDescOnce sync.Once
	file_resource_v2_endpoint_resource_proto_rawDescData []byte
)

func file_resource_v2_endpoint_resource_proto_rawDescGZIP() []byte {
	file_resource_v2_endpoint_resource_proto_rawDescOnce.Do(func() {
		file_resource_v2_endpoint_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v2_endpoint_resource_proto_rawDesc), len(file_resource_v2_endpoint_resource_proto_rawDesc)))
	})
	return file_resource_v2_endpoint_resource_proto_rawDescData
}

var file_resource_v2_endpoint_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_v2_endpoint_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_v2_endpoint_resource_proto_goTypes = []any{
	(EndpointStatus_State)(0), // 0: resource.v2.EndpointStatus.State
	(*AppEndpoint)(nil),       // 1: resource.v2.AppEndpoint
	(*Fqdn)(nil),              // 2: resource.v2.Fqdn
	(*Port)(nil),              // 3: resource.v2.Port
	(*EndpointStatus)(nil),    // 4: resource.v2.EndpointStatus
}
var file_resource_v2_endpoint_resource_proto_depIdxs = []int32{
	2, // 0: resource.v2.AppEndpoint.fqdns:type_name -> resource.v2.Fqdn
	3, // 1: resource.v2.AppEndpoint.ports:type_name -> resource.v2.Port
	4, // 2: resource.v2.AppEndpoint.endpoint_status:type_name -> resource.v2.EndpointStatus
	0, // 3: resource.v2.EndpointStatus.state:type_name -> resource.v2.EndpointStatus.State
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_v2_endpoint_resource_proto_init() }
func file_resource_v2_endpoint_resource_proto_init() {
	if File_resource_v2_endpoint_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v2_endpoint_resource_proto_rawDesc), len(file_resource_v2_endpoint_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v2_endpoint_resource_proto_goTypes,
		DependencyIndexes: file_resource_v2_endpoint_resource_proto_depIdxs,
		EnumInfos:         file_resource_v2_endpoint_resource_proto_enumTypes,
		MessageInfos:      file_resource_v2_endpoint_resource_proto_msgTypes,
	}.Build()
	File_resource_v2_endpoint_resource_proto = out.File
	file_resource_v2_endpoint_resource_proto_goTypes = nil
	file_resource_v2_endpoint_resource_proto_depIdxs = nil
}
