// SPDX-FileCopyrightText: (C) 2023 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: resource/v2/vm_resource.proto

package resourcev2

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminStatus_State int32

const (
	AdminStatus_STATE_UNSPECIFIED AdminStatus_State = 0
	AdminStatus_STATE_UP          AdminStatus_State = 1
	AdminStatus_STATE_DOWN        AdminStatus_State = 2
)

// Enum value maps for AdminStatus_State.
var (
	AdminStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_UP",
		2: "STATE_DOWN",
	}
	AdminStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_UP":          1,
		"STATE_DOWN":        2,
	}
)

func (x AdminStatus_State) Enum() *AdminStatus_State {
	p := new(AdminStatus_State)
	*p = x
	return p
}

func (x AdminStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_v2_vm_resource_proto_enumTypes[0].Descriptor()
}

func (AdminStatus_State) Type() protoreflect.EnumType {
	return &file_resource_v2_vm_resource_proto_enumTypes[0]
}

func (x AdminStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminStatus_State.Descriptor instead.
func (AdminStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_resource_v2_vm_resource_proto_rawDescGZIP(), []int{1, 0}
}

type VirtualMachineStatus_State int32

const (
	// indicates that the state of the virtual machine could not be obtained,
	// typically due to an error in communicating with the host on which it's running.
	VirtualMachineStatus_STATE_UNSPECIFIED VirtualMachineStatus_State = 0
	// indicates that the virtual machine is currently stopped and isn't expected to start.
	VirtualMachineStatus_STATE_STOPPED VirtualMachineStatus_State = 1
	// indicates that cluster resources associated with the virtual machine (e.g., DataVolumes)
	// are being provisioned and prepared.
	VirtualMachineStatus_STATE_PROVISIONING VirtualMachineStatus_State = 2
	// indicates that the virtual machine is being prepared for running.
	VirtualMachineStatus_STATE_STARTING VirtualMachineStatus_State = 3
	// indicates that the virtual machine is running.
	VirtualMachineStatus_STATE_RUNNING VirtualMachineStatus_State = 4
	// indicates that the virtual machine is paused.
	VirtualMachineStatus_STATE_PAUSED VirtualMachineStatus_State = 5
	// indicates that the virtual machine is in the process of being stopped.
	VirtualMachineStatus_STATE_STOPPING VirtualMachineStatus_State = 6
	// indicates that the virtual machine is in the process of deletion,
	// as well as its associated resources (VirtualMachineInstance, DataVolumes, …).
	VirtualMachineStatus_STATE_TERMINATING VirtualMachineStatus_State = 7
	// indicates that the virtual machine is currently in a crash loop waiting to be retried.
	VirtualMachineStatus_STATE_CRASH_LOOP_BACKOFF VirtualMachineStatus_State = 8
	// indicates that the virtual machine is in the process of being migrated to another host.
	VirtualMachineStatus_STATE_MIGRATING VirtualMachineStatus_State = 9
	// indicates that an error has occurred while scheduling the virtual machine,
	//
	//	e.g. due to unsatisfiable resource requests or unsatisfiable scheduling constraints.
	VirtualMachineStatus_STATE_ERROR_UNSCHEDULABLE VirtualMachineStatus_State = 10
	// indicates that an error has occurred while pulling an image for
	// a containerDisk VM volume.
	VirtualMachineStatus_STATE_ERROR_IMAGE_PULL VirtualMachineStatus_State = 11
	// indicates that an error has occurred while pulling an image for
	// a containerDisk VM volume, and that kubelet is backing off before retrying.
	VirtualMachineStatus_STATE_ERROR_IMAGE_PULL_BACKOFF VirtualMachineStatus_State = 12
	// indicates that the virtual machine references a PVC volume which doesn't exist.
	VirtualMachineStatus_STATE_ERROR_PVC_NOT_FOUND VirtualMachineStatus_State = 13
	// indicates that an error has been reported by one of the DataVolumes
	//
	//	referenced by the virtual machines.
	VirtualMachineStatus_STATE_ERROR_DATA_VOLUME VirtualMachineStatus_State = 14
	// indicates that some PersistentVolumeClaims backing
	// the virtual machine volume are still not bound.
	VirtualMachineStatus_STATE_WAITING_FOR_VOLUME_BINDING VirtualMachineStatus_State = 15
)

// Enum value maps for VirtualMachineStatus_State.
var (
	VirtualMachineStatus_State_name = map[int32]string{
		0:  "STATE_UNSPECIFIED",
		1:  "STATE_STOPPED",
		2:  "STATE_PROVISIONING",
		3:  "STATE_STARTING",
		4:  "STATE_RUNNING",
		5:  "STATE_PAUSED",
		6:  "STATE_STOPPING",
		7:  "STATE_TERMINATING",
		8:  "STATE_CRASH_LOOP_BACKOFF",
		9:  "STATE_MIGRATING",
		10: "STATE_ERROR_UNSCHEDULABLE",
		11: "STATE_ERROR_IMAGE_PULL",
		12: "STATE_ERROR_IMAGE_PULL_BACKOFF",
		13: "STATE_ERROR_PVC_NOT_FOUND",
		14: "STATE_ERROR_DATA_VOLUME",
		15: "STATE_WAITING_FOR_VOLUME_BINDING",
	}
	VirtualMachineStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED":                0,
		"STATE_STOPPED":                    1,
		"STATE_PROVISIONING":               2,
		"STATE_STARTING":                   3,
		"STATE_RUNNING":                    4,
		"STATE_PAUSED":                     5,
		"STATE_STOPPING":                   6,
		"STATE_TERMINATING":                7,
		"STATE_CRASH_LOOP_BACKOFF":         8,
		"STATE_MIGRATING":                  9,
		"STATE_ERROR_UNSCHEDULABLE":        10,
		"STATE_ERROR_IMAGE_PULL":           11,
		"STATE_ERROR_IMAGE_PULL_BACKOFF":   12,
		"STATE_ERROR_PVC_NOT_FOUND":        13,
		"STATE_ERROR_DATA_VOLUME":          14,
		"STATE_WAITING_FOR_VOLUME_BINDING": 15,
	}
)

func (x VirtualMachineStatus_State) Enum() *VirtualMachineStatus_State {
	p := new(VirtualMachineStatus_State)
	*p = x
	return p
}

func (x VirtualMachineStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualMachineStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_v2_vm_resource_proto_enumTypes[1].Descriptor()
}

func (VirtualMachineStatus_State) Type() protoreflect.EnumType {
	return &file_resource_v2_vm_resource_proto_enumTypes[1]
}

func (x VirtualMachineStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualMachineStatus_State.Descriptor instead.
func (VirtualMachineStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_resource_v2_vm_resource_proto_rawDescGZIP(), []int{2, 0}
}

// Represents a virtual machine.
type VirtualMachine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The virtual machine current status
	Status *VirtualMachineStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// The admin status whether the associated VirtualMachineInstance is created or not
	AdminStatus   *AdminStatus `protobuf:"bytes,2,opt,name=admin_status,json=adminStatus,proto3" json:"admin_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachine) Reset() {
	*x = VirtualMachine{}
	mi := &file_resource_v2_vm_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachine) ProtoMessage() {}

func (x *VirtualMachine) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachine.ProtoReflect.Descriptor instead.
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_resource_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachine) GetStatus() *VirtualMachineStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VirtualMachine) GetAdminStatus() *AdminStatus {
	if x != nil {
		return x.AdminStatus
	}
	return nil
}

// Represents the associated VirtualMachineInstance's state, either created (up state) or not (down state).
type AdminStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State information
	State         AdminStatus_State `protobuf:"varint,1,opt,name=state,proto3,enum=resource.v2.AdminStatus_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatus) Reset() {
	*x = AdminStatus{}
	mi := &file_resource_v2_vm_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatus) ProtoMessage() {}

func (x *AdminStatus) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatus.ProtoReflect.Descriptor instead.
func (*AdminStatus) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_resource_proto_rawDescGZIP(), []int{1}
}

func (x *AdminStatus) GetState() AdminStatus_State {
	if x != nil {
		return x.State
	}
	return AdminStatus_STATE_UNSPECIFIED
}

// Status of a virtual machine.
type VirtualMachineStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Virtual machine state
	State         VirtualMachineStatus_State `protobuf:"varint,1,opt,name=state,proto3,enum=resource.v2.VirtualMachineStatus_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachineStatus) Reset() {
	*x = VirtualMachineStatus{}
	mi := &file_resource_v2_vm_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineStatus) ProtoMessage() {}

func (x *VirtualMachineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineStatus.ProtoReflect.Descriptor instead.
func (*VirtualMachineStatus) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_resource_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualMachineStatus) GetState() VirtualMachineStatus_State {
	if x != nil {
		return x.State
	}
	return VirtualMachineStatus_STATE_UNSPECIFIED
}

var File_resource_v2_vm_resource_proto protoreflect.FileDescriptor

const file_resource_v2_vm_resource_proto_rawDesc = "" +
	"\n" +
	"\x1dresource/v2/vm_resource.proto\x12\vresource.v2\x1a\x1fgoogle/api/field_behavior.proto\"\x92\x01\n" +
	"\x0eVirtualMachine\x12>\n" +
	"\x06status\x18\x01 \x01(\v2!.resource.v2.VirtualMachineStatusB\x03\xe0A\x03R\x06status\x12@\n" +
	"\fadmin_status\x18\x02 \x01(\v2\x18.resource.v2.AdminStatusB\x03\xe0A\x03R\vadminStatus\"\x81\x01\n" +
	"\vAdminStatus\x124\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1e.resource.v2.AdminStatus.StateR\x05state\"<\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSTATE_UP\x10\x01\x12\x0e\n" +
	"\n" +
	"STATE_DOWN\x10\x02\"\xf9\x03\n" +
	"\x14VirtualMachineStatus\x12=\n" +
	"\x05state\x18\x01 \x01(\x0e2'.resource.v2.VirtualMachineStatus.StateR\x05state\"\xa1\x03\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_STOPPED\x10\x01\x12\x16\n" +
	"\x12STATE_PROVISIONING\x10\x02\x12\x12\n" +
	"\x0eSTATE_STARTING\x10\x03\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x04\x12\x10\n" +
	"\fSTATE_PAUSED\x10\x05\x12\x12\n" +
	"\x0eSTATE_STOPPING\x10\x06\x12\x15\n" +
	"\x11STATE_TERMINATING\x10\a\x12\x1c\n" +
	"\x18STATE_CRASH_LOOP_BACKOFF\x10\b\x12\x13\n" +
	"\x0fSTATE_MIGRATING\x10\t\x12\x1d\n" +
	"\x19STATE_ERROR_UNSCHEDULABLE\x10\n" +
	"\x12\x1a\n" +
	"\x16STATE_ERROR_IMAGE_PULL\x10\v\x12\"\n" +
	"\x1eSTATE_ERROR_IMAGE_PULL_BACKOFF\x10\f\x12\x1d\n" +
	"\x19STATE_ERROR_PVC_NOT_FOUND\x10\r\x12\x1b\n" +
	"\x17STATE_ERROR_DATA_VOLUME\x10\x0e\x12$\n" +
	" STATE_WAITING_FOR_VOLUME_BINDING\x10\x0fB\xd9\x01\n" +
	"\x0fcom.resource.v2B\x0fVmResourceProtoP\x01Zhgithub.com/open-edge-platform/app-orch-deployment/app-resource-manager/api/nbi/v2/resource/v2;resourcev2\xa2\x02\x03RXX\xaa\x02\vResource.V2\xca\x02\vResource\\V2\xe2\x02\x17Resource\\V2\\GPBMetadata\xea\x02\fResource::V2b\x06proto3"

var (
	file_resource_v2_vm_resource_proto_rawDescOnce sync.Once
	file_resource_v2_vm_resource_proto_rawDescData []byte
)

func file_resource_v2_vm_resource_proto_rawDescGZIP() []byte {
	file_resource_v2_vm_resource_proto_rawDescOnce.Do(func() {
		file_resource_v2_vm_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v2_vm_resource_proto_rawDesc), len(file_resource_v2_vm_resource_proto_rawDesc)))
	})
	return file_resource_v2_vm_resource_proto_rawDescData
}

var file_resource_v2_vm_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_resource_v2_vm_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resource_v2_vm_resource_proto_goTypes = []any{
	(AdminStatus_State)(0),          // 0: resource.v2.AdminStatus.State
	(VirtualMachineStatus_State)(0), // 1: resource.v2.VirtualMachineStatus.State
	(*VirtualMachine)(nil),          // 2: resource.v2.VirtualMachine
	(*AdminStatus)(nil),             // 3: resource.v2.AdminStatus
	(*VirtualMachineStatus)(nil),    // 4: resource.v2.VirtualMachineStatus
}
var file_resource_v2_vm_resource_proto_depIdxs = []int32{
	4, // 0: resource.v2.VirtualMachine.status:type_name -> resource.v2.VirtualMachineStatus
	3, // 1: resource.v2.VirtualMachine.admin_status:type_name -> resource.v2.AdminStatus
	0, // 2: resource.v2.AdminStatus.state:type_name -> resource.v2.AdminStatus.State
	1, // 3: resource.v2.VirtualMachineStatus.state:type_name -> resource.v2.VirtualMachineStatus.State
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_v2_vm_resource_proto_init() }
func file_resource_v2_vm_resource_proto_init() {
	if File_resource_v2_vm_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v2_vm_resource_proto_rawDesc), len(file_resource_v2_vm_resource_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_v2_vm_resource_proto_goTypes,
		DependencyIndexes: file_resource_v2_vm_resource_proto_depIdxs,
		EnumInfos:         file_resource_v2_vm_resource_proto_enumTypes,
		MessageInfos:      file_resource_v2_vm_resource_proto_msgTypes,
	}.Build()
	File_resource_v2_vm_resource_proto = out.File
	file_resource_v2_vm_resource_proto_goTypes = nil
	file_resource_v2_vm_resource_proto_depIdxs = nil
}
