// SPDX-FileCopyrightText: (C) 2023 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: resource/v2/vm_service.proto

package resourcev2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for StartVirtualMachine method
type StartVirtualMachineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Cluster ID
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Virtual machine ID
	VirtualMachineId string `protobuf:"bytes,3,opt,name=virtual_machine_id,json=virtualMachineId,proto3" json:"virtual_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartVirtualMachineRequest) Reset() {
	*x = StartVirtualMachineRequest{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVirtualMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVirtualMachineRequest) ProtoMessage() {}

func (x *StartVirtualMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVirtualMachineRequest.ProtoReflect.Descriptor instead.
func (*StartVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartVirtualMachineRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StartVirtualMachineRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *StartVirtualMachineRequest) GetVirtualMachineId() string {
	if x != nil {
		return x.VirtualMachineId
	}
	return ""
}

// Response message for the StartVirtualMachine method.
type StartVirtualMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVirtualMachineResponse) Reset() {
	*x = StartVirtualMachineResponse{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVirtualMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVirtualMachineResponse) ProtoMessage() {}

func (x *StartVirtualMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVirtualMachineResponse.ProtoReflect.Descriptor instead.
func (*StartVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{1}
}

// Request message for StopVirtualMachine method
type StopVirtualMachineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Cluster ID
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Virtual machine ID
	VirtualMachineId string `protobuf:"bytes,3,opt,name=virtual_machine_id,json=virtualMachineId,proto3" json:"virtual_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StopVirtualMachineRequest) Reset() {
	*x = StopVirtualMachineRequest{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVirtualMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVirtualMachineRequest) ProtoMessage() {}

func (x *StopVirtualMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVirtualMachineRequest.ProtoReflect.Descriptor instead.
func (*StopVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{2}
}

func (x *StopVirtualMachineRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StopVirtualMachineRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *StopVirtualMachineRequest) GetVirtualMachineId() string {
	if x != nil {
		return x.VirtualMachineId
	}
	return ""
}

// Response message for the StopVirtualMachine method.
type StopVirtualMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVirtualMachineResponse) Reset() {
	*x = StopVirtualMachineResponse{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVirtualMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVirtualMachineResponse) ProtoMessage() {}

func (x *StopVirtualMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVirtualMachineResponse.ProtoReflect.Descriptor instead.
func (*StopVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{3}
}

// Request message for RestartVirtualMachine method
type RestartVirtualMachineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Cluster ID
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Virtual machine ID
	VirtualMachineId string `protobuf:"bytes,3,opt,name=virtual_machine_id,json=virtualMachineId,proto3" json:"virtual_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestartVirtualMachineRequest) Reset() {
	*x = RestartVirtualMachineRequest{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartVirtualMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartVirtualMachineRequest) ProtoMessage() {}

func (x *RestartVirtualMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartVirtualMachineRequest.ProtoReflect.Descriptor instead.
func (*RestartVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{4}
}

func (x *RestartVirtualMachineRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RestartVirtualMachineRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RestartVirtualMachineRequest) GetVirtualMachineId() string {
	if x != nil {
		return x.VirtualMachineId
	}
	return ""
}

// Response message for the RestartVirtualMachine method.
type RestartVirtualMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartVirtualMachineResponse) Reset() {
	*x = RestartVirtualMachineResponse{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartVirtualMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartVirtualMachineResponse) ProtoMessage() {}

func (x *RestartVirtualMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartVirtualMachineResponse.ProtoReflect.Descriptor instead.
func (*RestartVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{5}
}

// Request message for GetVNC method
type GetVNCRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Cluster ID
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Virtual machine ID
	VirtualMachineId string `protobuf:"bytes,3,opt,name=virtual_machine_id,json=virtualMachineId,proto3" json:"virtual_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetVNCRequest) Reset() {
	*x = GetVNCRequest{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVNCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVNCRequest) ProtoMessage() {}

func (x *GetVNCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVNCRequest.ProtoReflect.Descriptor instead.
func (*GetVNCRequest) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetVNCRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetVNCRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GetVNCRequest) GetVirtualMachineId() string {
	if x != nil {
		return x.VirtualMachineId
	}
	return ""
}

// Response message for the GetVNC method.
type GetVNCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVNCResponse) Reset() {
	*x = GetVNCResponse{}
	mi := &file_resource_v2_vm_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVNCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVNCResponse) ProtoMessage() {}

func (x *GetVNCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v2_vm_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVNCResponse.ProtoReflect.Descriptor instead.
func (*GetVNCResponse) Descriptor() ([]byte, []int) {
	return file_resource_v2_vm_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetVNCResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_resource_v2_vm_service_proto protoreflect.FileDescriptor

const file_resource_v2_vm_service_proto_rawDesc = "" +
	"\n" +
	"\x1cresource/v2/vm_service.proto\x12\vresource.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bbuf/validate/validate.proto\"\xf9\x01\n" +
	"\x1aStartVirtualMachineRequest\x12K\n" +
	"\x06app_id\x18\x01 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18P2&^[a-z0-9][a-z0-9-]{0,78}[a-z0-9]{0,1}$R\x05appId\x12S\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\tclusterId\x129\n" +
	"\x12virtual_machine_id\x18\x03 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x10virtualMachineId\"\x1d\n" +
	"\x1bStartVirtualMachineResponse\"\xf8\x01\n" +
	"\x19StopVirtualMachineRequest\x12K\n" +
	"\x06app_id\x18\x01 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18P2&^[a-z0-9][a-z0-9-]{0,78}[a-z0-9]{0,1}$R\x05appId\x12S\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\tclusterId\x129\n" +
	"\x12virtual_machine_id\x18\x03 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x10virtualMachineId\"\x1c\n" +
	"\x1aStopVirtualMachineResponse\"\xfb\x01\n" +
	"\x1cRestartVirtualMachineRequest\x12K\n" +
	"\x06app_id\x18\x01 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18P2&^[a-z0-9][a-z0-9-]{0,78}[a-z0-9]{0,1}$R\x05appId\x12S\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\tclusterId\x129\n" +
	"\x12virtual_machine_id\x18\x03 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x10virtualMachineId\"\x1f\n" +
	"\x1dRestartVirtualMachineResponse\"\xec\x01\n" +
	"\rGetVNCRequest\x12K\n" +
	"\x06app_id\x18\x01 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18P2&^[a-z0-9][a-z0-9-]{0,78}[a-z0-9]{0,1}$R\x05appId\x12S\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB4\xe0A\x02\xbaH.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\tclusterId\x129\n" +
	"\x12virtual_machine_id\x18\x03 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x10virtualMachineId\"/\n" +
	"\x0eGetVNCResponse\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tB\x03\xe0A\x02R\aaddress2\xee\x06\n" +
	"\x15VirtualMachineService\x12\xdc\x01\n" +
	"\x13StartVirtualMachine\x12'.resource.v2.StartVirtualMachineRequest\x1a(.resource.v2.StartVirtualMachineResponse\"r\x82\xd3\xe4\x93\x02l\x1aj/resource.orchestrator.apis/v2/workloads/virtual-machines/{app_id}/{cluster_id}/{virtual_machine_id}/start\x12\xd8\x01\n" +
	"\x12StopVirtualMachine\x12&.resource.v2.StopVirtualMachineRequest\x1a'.resource.v2.StopVirtualMachineResponse\"q\x82\xd3\xe4\x93\x02k\x1ai/resource.orchestrator.apis/v2/workloads/virtual-machines/{app_id}/{cluster_id}/{virtual_machine_id}/stop\x12\xe4\x01\n" +
	"\x15RestartVirtualMachine\x12).resource.v2.RestartVirtualMachineRequest\x1a*.resource.v2.RestartVirtualMachineResponse\"t\x82\xd3\xe4\x93\x02n\x1al/resource.orchestrator.apis/v2/workloads/virtual-machines/{app_id}/{cluster_id}/{virtual_machine_id}/restart\x12\xb3\x01\n" +
	"\x06GetVNC\x12\x1a.resource.v2.GetVNCRequest\x1a\x1b.resource.v2.GetVNCResponse\"p\x82\xd3\xe4\x93\x02j\x12h/resource.orchestrator.apis/v2/workloads/virtual-machines/{app_id}/{cluster_id}/{virtual_machine_id}/vncB\xd8\x01\n" +
	"\x0fcom.resource.v2B\x0eVmServiceProtoP\x01Zhgithub.com/open-edge-platform/app-orch-deployment/app-resource-manager/api/nbi/v2/resource/v2;resourcev2\xa2\x02\x03RXX\xaa\x02\vResource.V2\xca\x02\vResource\\V2\xe2\x02\x17Resource\\V2\\GPBMetadata\xea\x02\fResource::V2b\x06proto3"

var (
	file_resource_v2_vm_service_proto_rawDescOnce sync.Once
	file_resource_v2_vm_service_proto_rawDescData []byte
)

func file_resource_v2_vm_service_proto_rawDescGZIP() []byte {
	file_resource_v2_vm_service_proto_rawDescOnce.Do(func() {
		file_resource_v2_vm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v2_vm_service_proto_rawDesc), len(file_resource_v2_vm_service_proto_rawDesc)))
	})
	return file_resource_v2_vm_service_proto_rawDescData
}

var file_resource_v2_vm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_resource_v2_vm_service_proto_goTypes = []any{
	(*StartVirtualMachineRequest)(nil),    // 0: resource.v2.StartVirtualMachineRequest
	(*StartVirtualMachineResponse)(nil),   // 1: resource.v2.StartVirtualMachineResponse
	(*StopVirtualMachineRequest)(nil),     // 2: resource.v2.StopVirtualMachineRequest
	(*StopVirtualMachineResponse)(nil),    // 3: resource.v2.StopVirtualMachineResponse
	(*RestartVirtualMachineRequest)(nil),  // 4: resource.v2.RestartVirtualMachineRequest
	(*RestartVirtualMachineResponse)(nil), // 5: resource.v2.RestartVirtualMachineResponse
	(*GetVNCRequest)(nil),                 // 6: resource.v2.GetVNCRequest
	(*GetVNCResponse)(nil),                // 7: resource.v2.GetVNCResponse
}
var file_resource_v2_vm_service_proto_depIdxs = []int32{
	0, // 0: resource.v2.VirtualMachineService.StartVirtualMachine:input_type -> resource.v2.StartVirtualMachineRequest
	2, // 1: resource.v2.VirtualMachineService.StopVirtualMachine:input_type -> resource.v2.StopVirtualMachineRequest
	4, // 2: resource.v2.VirtualMachineService.RestartVirtualMachine:input_type -> resource.v2.RestartVirtualMachineRequest
	6, // 3: resource.v2.VirtualMachineService.GetVNC:input_type -> resource.v2.GetVNCRequest
	1, // 4: resource.v2.VirtualMachineService.StartVirtualMachine:output_type -> resource.v2.StartVirtualMachineResponse
	3, // 5: resource.v2.VirtualMachineService.StopVirtualMachine:output_type -> resource.v2.StopVirtualMachineResponse
	5, // 6: resource.v2.VirtualMachineService.RestartVirtualMachine:output_type -> resource.v2.RestartVirtualMachineResponse
	7, // 7: resource.v2.VirtualMachineService.GetVNC:output_type -> resource.v2.GetVNCResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_v2_vm_service_proto_init() }
func file_resource_v2_vm_service_proto_init() {
	if File_resource_v2_vm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v2_vm_service_proto_rawDesc), len(file_resource_v2_vm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_v2_vm_service_proto_goTypes,
		DependencyIndexes: file_resource_v2_vm_service_proto_depIdxs,
		MessageInfos:      file_resource_v2_vm_service_proto_msgTypes,
	}.Build()
	File_resource_v2_vm_service_proto = out.File
	file_resource_v2_vm_service_proto_goTypes = nil
	file_resource_v2_vm_service_proto_depIdxs = nil
}
