# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.4.2"
description: Application Service Proxy
annotations:
  revision: "a4e6fa8"
  created: "2025-05-19T13:42:21Z"
appVersion: 1.4.2
