# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.5.4-dev"
description: Application Service Proxy
annotations:
  revision: "a137f0d"
  created: "2025-11-25T06:27:44Z"
appVersion: 1.5.4-dev-a137f0d
