# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.5.2"
description: Application Service Proxy
annotations:
  revision: "1fdc825"
  created: "2025-11-04T11:33:04Z"
appVersion: 1.5.2
