# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.6.0"
description: Application Service Proxy
annotations:
  revision: "a55c594"
  created: "2026-01-27T04:25:41Z"
appVersion: 1.6.0
