# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.6.2-dev"
description: Application Service Proxy
annotations:
  revision: "248e56d"
  created: "2026-03-02T07:26:28Z"
appVersion: 1.6.2-dev-248e56d
