# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.7.0-dev"
description: Application Service Proxy
annotations:
  revision: "41e3c25"
  created: "2026-03-20T08:37:48Z"
appVersion: 1.7.0-dev-41e3c25
