# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.7.1-dev"
description: Application Service Proxy
annotations:
  revision: "118d978"
  created: "2026-04-01T13:52:25Z"
appVersion: 1.7.1-dev-118d978
