# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.5.2-dev"
description: Application Service Proxy
annotations:
  revision: "074ee3e"
  created: "2025-11-03T16:21:14Z"
appVersion: 1.5.2-dev-074ee3e
