# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.6.1"
description: Application Service Proxy
annotations:
  revision: "77d030b"
  created: "2026-02-26T06:21:31Z"
appVersion: 1.6.1
