# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy
version: "1.3.22"
description: Application Service Proxy
annotations:
  revision: "d0f0b2e"
  created: "2025-04-09T22:42:18Z"
appVersion: 1.3.22
