# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.openpolicyagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app-service-proxy.fullname" . }}-opa-rego
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "files/openpolicyagent/*.rego").AsConfig | indent 2 }}
{{- end}}
