# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
{{- $registry := .Values.global.registry -}}
{{- if .Values.image.registry -}}
{{- $registry = .Values.image.registry -}}
{{- end -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app-service-proxy.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-service-proxy.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-service-proxy.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "app-service-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with $registry.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: app-service-proxy
        {{- with .Values.image }}
        image: "{{- if hasKey $registry "name" }}{{ $registry.name }}/{{- end -}}{{ .repository }}:{{ default $.Chart.AppVersion .tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/app-service-proxy" ]
        env:
          - name: MAX_BODY_SIZE_BYTES_LIMIT
            value: {{ .Values.conf.maxBodySizeBytesLimit | quote }}
          - name: API_POSITION_IN_URL
            value: {{ .Values.conf.apiPositionInUrl | quote }}
          - name: OIDC_SERVER_URL
            value: {{ .Values.openidc.issuer }}
          - name: OIDC_TLS_INSECURE_SKIP_VERIFY
            value: {{ .Values.openidc.insecureSkipVerify | quote }}
          - name: OPA_PORT
            value: {{ .Values.openpolicyagent.port | quote }}
          - name: USE_M2M_TOKEN
            value: {{  .Values.useM2MToken | quote }}
          {{- if .Values.openpolicyagent.enabled }}
          - name: OPA_ENABLED
            value: "true"
          {{- end}}
          - name: ASP_LOG_LEVEL
            value: {{ .Values.logLevel }}
          - name: ADM_ADDRESS
            value: {{ .Values.admAddress }}
          - name: CCG_ADDRESS
            value: {{ .Values.ccgAddress }}
          - name: RATE_LIMITER_QPS
            value: {{ .Values.admRateLimiter.qps | quote }}
          - name: RATE_LIMITER_BURST
            value: {{ .Values.admRateLimiter.burst | quote }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: asptmp
            mountPath: /tmp
      {{- if .Values.openpolicyagent.enabled }}
      - name: openpolicyagent
        {{- with .Values.openpolicyagent }}
        image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .image }}:{{ .tag }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: opa
            containerPort: {{ .Values.openpolicyagent.port }}
            protocol: TCP
        args:
          - "run"
          - "--server"
          - "/opt/app-service-proxy/rego"
          - "--log-level"
          - {{ .Values.openpolicyagent.loglevel }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health?bundle=true  # Include bundle activation in readiness
            scheme: HTTP
            port: {{ .Values.openpolicyagent.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health?bundle=true  # Include bundle activation in readiness
            scheme: HTTP
            port: {{ .Values.openpolicyagent.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: openpolicyagent
            mountPath: /opt/app-service-proxy/rego
            readOnly: true
       {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: asptmp
          emptyDir: {}
        {{- if .Values.openpolicyagent.enabled }}
        - name: openpolicyagent
          configMap:
            name: {{ include "app-service-proxy.fullname" . }}-opa-rego
        {{- end }}
