# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
  {{- include "app-service-proxy.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-cluster-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cluster-controller
subjects:
- kind: ServiceAccount
  name: {{ template "app-service-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
