# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-service-proxy.fullname" . }}
spec:
  type: {{ .Values.service.apiProxy.type }}
  selector:
    {{- include "app-service-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.apiProxy.port }}
    {{- if eq .Values.service.apiProxy.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
---
{{- if .Values.traefik.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app-service-proxy.fullname" . }}
  namespace: {{ .Values.traefik.gatewayNamespace }}
spec:
  headers:
    customRequestHeaders:
      Host: {{ include "app-service-proxy.fullname" . }}.{{ .Release.Namespace }}.svc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app-service-proxy.fullname" . }}
  namespace: {{ .Values.traefik.gatewayNamespace }}
spec:
  entryPoints: # We listen to requests coming from ports 443
    - websecure
  routes:
    - match: {{ required "Traefik route match is required!" .Values.traefik.matchRoute }}
      kind: Rule
      middlewares:
        - name: {{ include "app-service-proxy.fullname" . }}
      services:
        - name: {{ include "app-service-proxy.fullname" . }}
          port: {{ .Values.service.apiProxy.port }}
          scheme: http
          namespace: {{ .Release.Namespace }}
  tls:
    # Use the secret generated by cert-manager that resides in gateway-system namespace
    secretName: {{ .Values.traefik.secretName }}
{{- if .Values.traefik.tlsOption }}
    options:
      name: {{ .Values.traefik.tlsOption }}
      namespace: {{ .Values.traefik.gatewayNamespace }}
{{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ws-{{ include "app-service-proxy.fullname" . }}
  namespace: {{ .Values.traefik.gatewayNamespace }}
spec:
  entryPoints: # We listen to requests coming from ports 443
    - websecure
  routes:
    - match: {{ required "Traefik route match is required!" .Values.traefik.matchRouteWs }}
      kind: Rule
      middlewares:
        - name: {{ include "app-service-proxy.fullname" . }}
      services:
        - name: {{ include "app-service-proxy.fullname" . }}
          port: {{ .Values.service.apiProxy.port }}
          scheme: http
          namespace: {{ .Release.Namespace }}
  tls:
    # Use the secret generated by cert-manager that resides in gateway-system namespace
    secretName: {{ .Values.traefik.secretName }}
{{- if .Values.traefik.tlsOption }}
    options:
      name: {{ .Values.traefik.tlsOption }}
      namespace: {{ .Values.traefik.gatewayNamespace }}
{{- end }}
{{- end }}
---
{{- if .Values.openpolicyagent.enabled -}}
{{- if .Values.service.opa.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-service-proxy.fullname" . }}-opa
  labels:
    {{- include "app-service-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.opa.type }}
  ports:
    - port: {{ .Values.service.opa.port }}
      protocol: TCP
      name: http-opa
  selector:
    {{- include "app-service-proxy.selectorLabels" . | nindent 4 }}
{{- end}}
{{- end}}
