# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: app-service-proxy-agent
description: Application Service Proxy Agent
# Correct version will be added by "make helm-package" from VERSION
version: 1.3.4
annotations:
  revision: "60a3a71"
  created: "2025-04-08T09:36:26Z"
appVersion: 1.3.4
