# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##

## @param global.registry.name Global Docker image registry
## @param global.registry.imagePullSecrets Global Docker registry secret names as an array
##
global:
  registry:
    name: registry-rs.edgeorchestration.intel.com/edge-orch
    ## E.g.
    ## imagePullSecrets:
    ##   - myRegistryKeySecretName
    ##
    imagePullSecrets: []

## @section App-Service-Proxy agent image parameters
##

## @param image.registry.name App-Service-Proxy agent Docker image registry
## @param image.registry.imagePullSecrets App-Service-Proxy agent Docker registry secret names as an array
## @param image.repository App-Service-Proxy agent image repository
## @param image.pullPolicy App=Service-Proxy agent image pull policy
## @skip image.tag App-Service-Proxy agent image tag (immutable tags are recommended)
image:
  registry:
    name: registry-rs.edgeorchestration.intel.com/edge-orch
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    imagePullSecrets: []
  repository: app/app-service-proxy-agent
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
  ##
  pullPolicy: IfNotPresent
  #tag:

## @section Common parameters
##

## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname template
##
fullnameOverride: ""

## @param replicaCount Number of App-Service-Proxy agent replicas to deploy
##
replicaCount: 1

## @param podLabels Extra labels for App-Service-Proxy agent pod
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## @param podAnnotations Annotations for App-Service-Proxy agent pod
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## App-Service-Proxy agent containers' resource requests and limits
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
## @param resources.limits The resources limits for the App-Service-Proxy agent containers
## @param resources.requests.memory The requested memory for the App-Service-Proxy agent containers
## @param resources.requests.cpu The requested cpu for the App-Service-Proxy agent containers
##
resources:
  limits: {}
  requests:
    memory: 128Mi
    cpu: 100m

## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext:
  #runAsGroup:
  runAsUser: 65532
  runAsNonRoot: true

## Configure Container Security Context (only main container)
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - "ALL"

## App-Service-Proxy agent Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  ## @param serviceAccount.create Enable creation of ServiceAccount for App-Service-Proxy agent pod
  ##
  create: true

## @section App-Service-Proxy agent configuration
##

## App-Service-Proxy agent configuration
conf:
  ## @param conf.proxyDomain App-Service-Proxy server domain for the service traffic
  ## @param conf.proxyServerUrl App-Service-Proxy server URL for websocket connection
  ## @param conf.proxyServerCA App-Service-Proxy server certificate CA
  ## @param conf.insecureSkipVerify Disable SSL certificate validation when set true
  ## @param conf.agentId Identifier of the agent
  ## @param conf.agentToken Token to validate the connection request
  ## @param conf.agentTokenSecretName If set, agentToken is ignored and the secret is used
  ## @param conf.networkPolicies.allowedEndpoints additional network policy configs for the agent
  proxyDomain: "app-service-proxy.kind.internal"
  proxyServerURL: ""
  #proxyServerCA: ""
  insecureSkipVerify: "false"
  agentId: ""
  #agentToken: ""
  #agentTokenSecretName: "app-service-proxy-agent-token"
  networkPolicies:
    allowedEndpoints:
      - cidr: 0.0.0.0/0
        protocol: TCP
        port: 443

# Enables debug logging on the WS tunnel. Note that logLevel has to be set to "info" or below for this to have an effect.
remotedialer:
  debug: "false"

# Application-wide log level. Must be a valid logrus log level string.
logLevel: "warn"
