# SPDX-FileCopyrightText: (C) 2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: app-resource-manager
description: A Helm chart for Kubernetes
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 2.3.22
# Default appVersion will be overwritten by the build to use {repo}/VERSION. This
# value is supplied only to enable local unbuilt deployment of default released
# content.
appVersion: 2.3.22
annotations:
  revision: "11c0a3e"
  created: "2025-04-01T22:44:38Z"
