// SPDX-FileCopyrightText: (C) 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: deployment/v1/resources.proto

package deploymentv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State are the different states a deployment/cluster/app can be in.
type State int32

const (
	State_UNKNOWN            State = 0
	State_RUNNING            State = 1
	State_DOWN               State = 2
	State_INTERNAL_ERROR     State = 3
	State_DEPLOYING          State = 4
	State_UPDATING           State = 5
	State_TERMINATING        State = 6
	State_ERROR              State = 7
	State_NO_TARGET_CLUSTERS State = 8
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "UNKNOWN",
		1: "RUNNING",
		2: "DOWN",
		3: "INTERNAL_ERROR",
		4: "DEPLOYING",
		5: "UPDATING",
		6: "TERMINATING",
		7: "ERROR",
		8: "NO_TARGET_CLUSTERS",
	}
	State_value = map[string]int32{
		"UNKNOWN":            0,
		"RUNNING":            1,
		"DOWN":               2,
		"INTERNAL_ERROR":     3,
		"DEPLOYING":          4,
		"UPDATING":           5,
		"TERMINATING":        6,
		"ERROR":              7,
		"NO_TARGET_CLUSTERS": 8,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_deployment_v1_resources_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_deployment_v1_resources_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{0}
}

// Deployment defines the specification to deploy a Deployment Package onto a set of clusters.
type Deployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment name (unique string assigned by Orchestrator).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Deployment display name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The deployment package name to deploy from the catalog.
	AppName string `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// The version of the deployment package.
	AppVersion string `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// The selected profile name to be used for the base Helm values of the different applications in the deployment package
	ProfileName string `protobuf:"bytes,5,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	// The creation time of the deployment.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The id of the deployment.
	DeployId string `protobuf:"bytes,7,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	// The Override values can be used to override any of the base profile values based on Deployment scenario.
	OverrideValues []*OverrideValues `protobuf:"bytes,8,rep,name=override_values,json=overrideValues,proto3" json:"override_values,omitempty"`
	// Cluster labels on which we want to deploy the application.
	TargetClusters []*TargetClusters `protobuf:"bytes,9,rep,name=target_clusters,json=targetClusters,proto3" json:"target_clusters,omitempty"`
	// Status of the deployment.
	Status *Deployment_Status `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// Application details.
	Apps []*App `protobuf:"bytes,11,rep,name=apps,proto3" json:"apps,omitempty"`
	// The deployment type for the target cluster deployment can be either auto-scaling or targeted.
	// In Auto-scaling type, the application will be automatically deployed on all the
	// clusters which match the Target cluster label. In Targeted type, the user has to select among pre created
	// clusters to deploy the application.
	DeploymentType string `protobuf:"bytes,12,opt,name=deployment_type,json=deploymentType,proto3" json:"deployment_type,omitempty"`
	// network_name is the name of the interconnect network that deployment be part of
	NetworkName    string           `protobuf:"bytes,13,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	ServiceExports []*ServiceExport `protobuf:"bytes,14,rep,name=service_exports,json=serviceExports,proto3" json:"service_exports,omitempty"`
	// Cluster labels/clusterID on which we want to deploy all the applications of the
	// deployment package
	AllAppTargetClusters *TargetClusters `protobuf:"bytes,15,opt,name=all_app_target_clusters,json=allAppTargetClusters,proto3" json:"all_app_target_clusters,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_deployment_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Deployment) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Deployment) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Deployment) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *Deployment) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Deployment) GetDeployId() string {
	if x != nil {
		return x.DeployId
	}
	return ""
}

func (x *Deployment) GetOverrideValues() []*OverrideValues {
	if x != nil {
		return x.OverrideValues
	}
	return nil
}

func (x *Deployment) GetTargetClusters() []*TargetClusters {
	if x != nil {
		return x.TargetClusters
	}
	return nil
}

func (x *Deployment) GetStatus() *Deployment_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Deployment) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *Deployment) GetDeploymentType() string {
	if x != nil {
		return x.DeploymentType
	}
	return ""
}

func (x *Deployment) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *Deployment) GetServiceExports() []*ServiceExport {
	if x != nil {
		return x.ServiceExports
	}
	return nil
}

func (x *Deployment) GetAllAppTargetClusters() *TargetClusters {
	if x != nil {
		return x.AllAppTargetClusters
	}
	return nil
}

type ServiceExport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceExport) Reset() {
	*x = ServiceExport{}
	mi := &file_deployment_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceExport) ProtoMessage() {}

func (x *ServiceExport) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceExport.ProtoReflect.Descriptor instead.
func (*ServiceExport) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceExport) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ServiceExport) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// The Override values can be used to override any of the base helm values of
// applications based on Deployment scenario.
type OverrideValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deployment package name to use when overriding values.
	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// The namespace to deploy the app onto, default namespace is default.
	TargetNamespace string `protobuf:"bytes,2,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"`
	// The YAML representing Helm overrides
	Values        *structpb.Struct `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideValues) Reset() {
	*x = OverrideValues{}
	mi := &file_deployment_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideValues) ProtoMessage() {}

func (x *OverrideValues) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideValues.ProtoReflect.Descriptor instead.
func (*OverrideValues) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *OverrideValues) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *OverrideValues) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *OverrideValues) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

// Set target clusters based on labels.
type TargetClusters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The targeted deployment package name.
	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Cluster labels to match the target cluster when auto-scaling deployment.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Cluster id to match the target cluster when targeted deployment.
	ClusterId     string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetClusters) Reset() {
	*x = TargetClusters{}
	mi := &file_deployment_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetClusters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetClusters) ProtoMessage() {}

func (x *TargetClusters) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetClusters.ProtoReflect.Descriptor instead.
func (*TargetClusters) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *TargetClusters) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *TargetClusters) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TargetClusters) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// Count of status.
type Summary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total count of apps/clusters in the deployment, value from owned GitRepo objects.
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Number of running apps/clusters in the deployment, value from owned GitRepo objects.
	Running int32 `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	// Number of down apps/clusters in the deployment.
	Down int32 `protobuf:"varint,3,opt,name=down,proto3" json:"down,omitempty"`
	// Type of thing that we're counting, ie clusters, apps.
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Unknown status to indicate cluster not reachable.
	Unknown       int32 `protobuf:"varint,5,opt,name=unknown,proto3" json:"unknown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_deployment_v1_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{4}
}

func (x *Summary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Summary) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *Summary) GetDown() int32 {
	if x != nil {
		return x.Down
	}
	return 0
}

func (x *Summary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Summary) GetUnknown() int32 {
	if x != nil {
		return x.Unknown
	}
	return 0
}

// Details of application.
type App struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deployment package app name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Id of the app (same as Fleet bundle name) which is,
	// concatenated from name and deploy_id (uid which comes from k8s).
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Status has details of the app.
	Status        *Deployment_Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_deployment_v1_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{5}
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetStatus() *Deployment_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeploymentInstancesCluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment CR UID.
	DeploymentUid string `protobuf:"bytes,1,opt,name=deployment_uid,json=deploymentUid,proto3" json:"deployment_uid,omitempty"`
	// Deployment name (unique string assigned by Orchestrator).
	DeploymentName string `protobuf:"bytes,2,opt,name=deployment_name,json=deploymentName,proto3" json:"deployment_name,omitempty"`
	// Deployment display name.
	DeploymentDisplayName string `protobuf:"bytes,3,opt,name=deployment_display_name,json=deploymentDisplayName,proto3" json:"deployment_display_name,omitempty"`
	// Status has details of the cluster.
	Status *Deployment_Status `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Apps has per-app details.
	Apps          []*App `protobuf:"bytes,5,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentInstancesCluster) Reset() {
	*x = DeploymentInstancesCluster{}
	mi := &file_deployment_v1_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentInstancesCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentInstancesCluster) ProtoMessage() {}

func (x *DeploymentInstancesCluster) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentInstancesCluster.ProtoReflect.Descriptor instead.
func (*DeploymentInstancesCluster) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{6}
}

func (x *DeploymentInstancesCluster) GetDeploymentUid() string {
	if x != nil {
		return x.DeploymentUid
	}
	return ""
}

func (x *DeploymentInstancesCluster) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

func (x *DeploymentInstancesCluster) GetDeploymentDisplayName() string {
	if x != nil {
		return x.DeploymentDisplayName
	}
	return ""
}

func (x *DeploymentInstancesCluster) GetStatus() *Deployment_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DeploymentInstancesCluster) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

// Details of cluster.
type Cluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the display name which user provides and ECM creates and assigns clustername label to Fleet cluster object.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ID is the cluster id which ECM generates and assigns to the Rancher cluster name.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Status has details of the cluster.
	Status *Deployment_Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Apps has per-app details.
	Apps          []*App `protobuf:"bytes,4,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_deployment_v1_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{7}
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetStatus() *Deployment_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Cluster) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

// Status has details of the deployment.
type Deployment_Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=deployment.v1.State" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Summary       *Summary               `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment_Status) Reset() {
	*x = Deployment_Status{}
	mi := &file_deployment_v1_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment_Status) ProtoMessage() {}

func (x *Deployment_Status) ProtoReflect() protoreflect.Message {
	mi := &file_deployment_v1_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment_Status.ProtoReflect.Descriptor instead.
func (*Deployment_Status) Descriptor() ([]byte, []int) {
	return file_deployment_v1_resources_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Deployment_Status) GetState() State {
	if x != nil {
		return x.State
	}
	return State_UNKNOWN
}

func (x *Deployment_Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Deployment_Status) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

var File_deployment_v1_resources_proto protoreflect.FileDescriptor

const file_deployment_v1_resources_proto_rawDesc = "" +
	"\n" +
	"\x1ddeployment/v1/resources.proto\x12\rdeployment.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xea\t\n" +
	"\n" +
	"Deployment\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12c\n" +
	"\fdisplay_name\x18\x02 \x01(\tB@\xe0A\x01\xfaB:r8\x10\x00\x18(22^([a-zA-Z0-9][\\w\\- \\.\\/_]{0,38}[a-zA-Z0-9]{0,1}|)$R\vdisplayName\x12O\n" +
	"\bapp_name\x18\x03 \x01(\tB4\xe0A\x02\xfaB.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\aappName\x12V\n" +
	"\vapp_version\x18\x04 \x01(\tB5\xe0A\x02\xfaB/r-\x10\x01\x18\x142'^[a-z0-9][a-z0-9-.]{0,18}[a-z0-9]{0,1}$R\n" +
	"appVersion\x12X\n" +
	"\fprofile_name\x18\x05 \x01(\tB5\xe0A\x01\xfaB/r-\x10\x00\x18(2'^[a-z0-9]*[a-z0-9-]{0,38}[a-z0-9]{0,1}$R\vprofileName\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12 \n" +
	"\tdeploy_id\x18\a \x01(\tB\x03\xe0A\x03R\bdeployId\x12K\n" +
	"\x0foverride_values\x18\b \x03(\v2\x1d.deployment.v1.OverrideValuesB\x03\xe0A\x01R\x0eoverrideValues\x12K\n" +
	"\x0ftarget_clusters\x18\t \x03(\v2\x1d.deployment.v1.TargetClustersB\x03\xe0A\x01R\x0etargetClusters\x12=\n" +
	"\x06status\x18\n" +
	" \x01(\v2 .deployment.v1.Deployment.StatusB\x03\xe0A\x03R\x06status\x12+\n" +
	"\x04apps\x18\v \x03(\v2\x12.deployment.v1.AppB\x03\xe0A\x03R\x04apps\x12^\n" +
	"\x0fdeployment_type\x18\f \x01(\tB5\xe0A\x01\xfaB/r-\x10\x00\x18\x142'^[a-z0-9]*[a-z0-9-]{0,18}[a-z0-9]{0,1}$R\x0edeploymentType\x12X\n" +
	"\fnetwork_name\x18\r \x01(\tB5\xe0A\x01\xfaB/r-\x10\x00\x18(2'^[a-z0-9]*[a-z0-9-]{0,18}[a-z0-9]{0,1}$R\vnetworkName\x12J\n" +
	"\x0fservice_exports\x18\x0e \x03(\v2\x1c.deployment.v1.ServiceExportB\x03\xe0A\x01R\x0eserviceExports\x12Y\n" +
	"\x17all_app_target_clusters\x18\x0f \x01(\v2\x1d.deployment.v1.TargetClustersB\x03\xe0A\x01R\x14allAppTargetClusters\x1a\x8f\x01\n" +
	"\x06Status\x12/\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.deployment.v1.StateB\x03\xe0A\x03R\x05state\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tB\x03\xe0A\x03R\amessage\x125\n" +
	"\asummary\x18\x03 \x01(\v2\x16.deployment.v1.SummaryB\x03\xe0A\x03R\asummary\"z\n" +
	"\rServiceExport\x12O\n" +
	"\bapp_name\x18\x01 \x01(\tB4\xe0A\x02\xfaB.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\aappName\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\xfb\x01\n" +
	"\x0eOverrideValues\x12O\n" +
	"\bapp_name\x18\x01 \x01(\tB4\xe0A\x02\xfaB.r,\x10\x01\x18(2&^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\aappName\x12b\n" +
	"\x10target_namespace\x18\x02 \x01(\tB7\xe0A\x01\xfaB1r/\x10\x00\x18?2)(^$)|^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?$R\x0ftargetNamespace\x124\n" +
	"\x06values\x18\x03 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x01R\x06values\"\x8d\x02\n" +
	"\x0eTargetClusters\x12T\n" +
	"\bapp_name\x18\x01 \x01(\tB9\xe0A\x01\xfaB3r1\x10\x00\x18(2+(^$)|^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]{0,1}$R\aappName\x12F\n" +
	"\x06labels\x18\x02 \x03(\v2).deployment.v1.TargetClusters.LabelsEntryB\x03\xe0A\x01R\x06labels\x12\"\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tB\x03\xe0A\x01R\tclusterId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\aSummary\x12\x19\n" +
	"\x05total\x18\x01 \x01(\x05B\x03\xe0A\x03R\x05total\x12\x1d\n" +
	"\arunning\x18\x02 \x01(\x05B\x03\xe0A\x03R\arunning\x12\x17\n" +
	"\x04down\x18\x03 \x01(\x05B\x03\xe0A\x03R\x04down\x12\x17\n" +
	"\x04type\x18\x04 \x01(\tB\x03\xe0A\x03R\x04type\x12\x1d\n" +
	"\aunknown\x18\x05 \x01(\x05B\x03\xe0A\x03R\aunknown\"r\n" +
	"\x03App\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x03R\x02id\x12=\n" +
	"\x06status\x18\x03 \x01(\v2 .deployment.v1.Deployment.StatusB\x03\xe0A\x03R\x06status\"\xdc\x02\n" +
	"\x1aDeploymentInstancesCluster\x12*\n" +
	"\x0edeployment_uid\x18\x01 \x01(\tB\x03\xe0A\x03R\rdeploymentUid\x12,\n" +
	"\x0fdeployment_name\x18\x02 \x01(\tB\x03\xe0A\x03R\x0edeploymentName\x12x\n" +
	"\x17deployment_display_name\x18\x03 \x01(\tB@\xe0A\x01\xfaB:r8\x10\x00\x18(22^([a-zA-Z0-9][\\w\\- \\.\\/_]{0,38}[a-zA-Z0-9]{0,1}|)$R\x15deploymentDisplayName\x12=\n" +
	"\x06status\x18\x04 \x01(\v2 .deployment.v1.Deployment.StatusB\x03\xe0A\x03R\x06status\x12+\n" +
	"\x04apps\x18\x05 \x03(\v2\x12.deployment.v1.AppB\x03\xe0A\x03R\x04apps\"\xa3\x01\n" +
	"\aCluster\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x03R\x02id\x12=\n" +
	"\x06status\x18\x03 \x01(\v2 .deployment.v1.Deployment.StatusB\x03\xe0A\x03R\x06status\x12+\n" +
	"\x04apps\x18\x04 \x03(\v2\x12.deployment.v1.AppB\x03\xe0A\x03R\x04apps*\x90\x01\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\b\n" +
	"\x04DOWN\x10\x02\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x03\x12\r\n" +
	"\tDEPLOYING\x10\x04\x12\f\n" +
	"\bUPDATING\x10\x05\x12\x0f\n" +
	"\vTERMINATING\x10\x06\x12\t\n" +
	"\x05ERROR\x10\a\x12\x16\n" +
	"\x12NO_TARGET_CLUSTERS\x10\bB\xe8\x01\n" +
	"\x11com.deployment.v1B\x0eResourcesProtoP\x01Zngithub.com/open-edge-platform/app-orch-deployment/app-deployment-manager/api/nbi/v2/deployment/v1;deploymentv1\xa2\x02\x03DXX\xaa\x02\rDeployment.V1\xca\x02\rDeployment\\V1\xe2\x02\x19Deployment\\V1\\GPBMetadata\xea\x02\x0eDeployment::V1b\x06proto3"

var (
	file_deployment_v1_resources_proto_rawDescOnce sync.Once
	file_deployment_v1_resources_proto_rawDescData []byte
)

func file_deployment_v1_resources_proto_rawDescGZIP() []byte {
	file_deployment_v1_resources_proto_rawDescOnce.Do(func() {
		file_deployment_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployment_v1_resources_proto_rawDesc), len(file_deployment_v1_resources_proto_rawDesc)))
	})
	return file_deployment_v1_resources_proto_rawDescData
}

var file_deployment_v1_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deployment_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_deployment_v1_resources_proto_goTypes = []any{
	(State)(0),                         // 0: deployment.v1.State
	(*Deployment)(nil),                 // 1: deployment.v1.Deployment
	(*ServiceExport)(nil),              // 2: deployment.v1.ServiceExport
	(*OverrideValues)(nil),             // 3: deployment.v1.OverrideValues
	(*TargetClusters)(nil),             // 4: deployment.v1.TargetClusters
	(*Summary)(nil),                    // 5: deployment.v1.Summary
	(*App)(nil),                        // 6: deployment.v1.App
	(*DeploymentInstancesCluster)(nil), // 7: deployment.v1.DeploymentInstancesCluster
	(*Cluster)(nil),                    // 8: deployment.v1.Cluster
	(*Deployment_Status)(nil),          // 9: deployment.v1.Deployment.Status
	nil,                                // 10: deployment.v1.TargetClusters.LabelsEntry
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 12: google.protobuf.Struct
}
var file_deployment_v1_resources_proto_depIdxs = []int32{
	11, // 0: deployment.v1.Deployment.create_time:type_name -> google.protobuf.Timestamp
	3,  // 1: deployment.v1.Deployment.override_values:type_name -> deployment.v1.OverrideValues
	4,  // 2: deployment.v1.Deployment.target_clusters:type_name -> deployment.v1.TargetClusters
	9,  // 3: deployment.v1.Deployment.status:type_name -> deployment.v1.Deployment.Status
	6,  // 4: deployment.v1.Deployment.apps:type_name -> deployment.v1.App
	2,  // 5: deployment.v1.Deployment.service_exports:type_name -> deployment.v1.ServiceExport
	4,  // 6: deployment.v1.Deployment.all_app_target_clusters:type_name -> deployment.v1.TargetClusters
	12, // 7: deployment.v1.OverrideValues.values:type_name -> google.protobuf.Struct
	10, // 8: deployment.v1.TargetClusters.labels:type_name -> deployment.v1.TargetClusters.LabelsEntry
	9,  // 9: deployment.v1.App.status:type_name -> deployment.v1.Deployment.Status
	9,  // 10: deployment.v1.DeploymentInstancesCluster.status:type_name -> deployment.v1.Deployment.Status
	6,  // 11: deployment.v1.DeploymentInstancesCluster.apps:type_name -> deployment.v1.App
	9,  // 12: deployment.v1.Cluster.status:type_name -> deployment.v1.Deployment.Status
	6,  // 13: deployment.v1.Cluster.apps:type_name -> deployment.v1.App
	0,  // 14: deployment.v1.Deployment.Status.state:type_name -> deployment.v1.State
	5,  // 15: deployment.v1.Deployment.Status.summary:type_name -> deployment.v1.Summary
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_deployment_v1_resources_proto_init() }
func file_deployment_v1_resources_proto_init() {
	if File_deployment_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployment_v1_resources_proto_rawDesc), len(file_deployment_v1_resources_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deployment_v1_resources_proto_goTypes,
		DependencyIndexes: file_deployment_v1_resources_proto_depIdxs,
		EnumInfos:         file_deployment_v1_resources_proto_enumTypes,
		MessageInfos:      file_deployment_v1_resources_proto_msgTypes,
	}.Build()
	File_deployment_v1_resources_proto = out.File
	file_deployment_v1_resources_proto_goTypes = nil
	file_deployment_v1_resources_proto_depIdxs = nil
}
