# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress-proxy-agent
  {{- with .Values.podLabels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "app-service-proxy-agent.labels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress: []

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-proxy-and-k8sapi-proxy-agent
  {{- with .Values.podLabels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "app-service-proxy-agent.labels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  {{- if (lookup "v1" "Endpoints" "default" "kubernetes").subsets }}
  - to:
    - ipBlock:
        cidr: {{ printf "%s/32" (index (index (lookup "v1" "Endpoints" "default" "kubernetes").subsets 0).addresses 0).ip }}
    ports:
    - protocol: {{ (index (index (lookup "v1" "Endpoints" "default" "kubernetes").subsets 0).ports 0).protocol }}
      port: {{ (index (index (lookup "v1" "Endpoints" "default" "kubernetes").subsets 0).ports 0).port }}
  {{- end }}
  - to:
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  {{- range .Values.conf.networkPolicies.allowedEndpoints }}
  - to:
      - ipBlock:
          cidr: {{ .cidr | quote }}
    ports:
      - protocol: {{ .protocol }}
        port: {{ .port }}
  {{- end }}
