# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-proxy-agent
  labels:
    app.kubernetes.io/component: rbac
    {{- include "app-service-proxy-agent.labels" . | nindent 4 }}
{{- end }}
