# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
# permissions for end users to view deployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-deployment-manager
    app.kubernetes.io/part-of: app-deployment-manager
    app.kubernetes.io/managed-by: kustomize
  name: deployment-viewer-role
rules:
  - apiGroups:
      - app.edge-orchestrator.intel.com
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - app.edge-orchestrator.intel.com
    resources:
      - deployments/status
    verbs:
      - get
