---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.edge-orchestrator.intel.com
  resources:
  - clusters
  - deploymentclusters
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.edge-orchestrator.intel.com
  resources:
  - clusters/finalizers
  - deploymentclusters/finalizers
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - app.edge-orchestrator.intel.com
  resources:
  - clusters/status
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - app.edge-orchestrator.intel.com
  resources:
  - deploymentclusters/status
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundledeployments
  - bundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleet.cattle.io
  resources:
  - gitrepos
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
