# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: App Deployment Manager
name: app-deployment-manager
# Correct version will be added by "make helm-package" from VERSION
version: 2.7.0
annotations:
  revision: "8e44398"
  created: "2026-04-01T11:37:33Z"
appVersion: 2.7.0
