# SPDX-FileCopyrightText: (C) 2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-resource-manager.fullname" . }}
  labels:
    {{- include "app-resource-manager.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4}}
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}

---

{{ if .Values.openpolicyagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app-resource-manager.fullname" . }}-opa-rego-v2
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "files/openpolicyagent/v2/*.rego").AsConfig | indent 2 }}
{{- end}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-resource-manager.fullname" . }}-dashboard
  labels:
    grafana_admin_dashboard: "1"
    {{- include "app-resource-manager.labels" . | nindent 4 }}
  annotations:
    grafana_folder: "Orchestrator"
data:
{{ (.Files.Glob "files/grafana/*.json").AsConfig | indent 2 }}
