{{- $registry := .Values.global.registry -}}
{{- if .Values.image.registry -}}
{{- $registry = .Values.image.registry -}}
{{- end -}}

# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vnc-proxy.fullname" . }}
  labels:
    {{- include "vnc-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vncProxyReplicaCount }}
  selector:
    matchLabels:
      {{- include "vnc-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vnc-proxy.selectorLabels" . | nindent 8 }}
        version: {{ .Chart.AppVersion | quote }}
    spec:
      {{- with $registry.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "app-resource-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.openpolicyagent.enabled }}
        - name: openpolicyagent
          securityContext:
              {{- toYaml .Values.opaSecurityContext | nindent 12 }}
          resources:
              {{- toYaml .Values.vncProxyResources | nindent 12 }}
          {{- with .Values.openpolicyagent }}
          image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .image }}:{{ .tag }}"
          {{- end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: opa
              containerPort: {{ .Values.openpolicyagent.port }}
          args:
            - "run"
            - "--server"
            - /opt/vnc-proxy/rego/v2
            - "--log-level"
            - {{ .Values.openpolicyagent.loglevel }}
            - "--addr"
            - ":{{ .Values.openpolicyagent.port }}"
          livenessProbe:
            httpGet:
              path: /health?bundle=true  # Include bundle activation in readiness
              scheme: HTTP
              port: {{ .Values.openpolicyagent.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health?bundle=true  # Include bundle activation in readiness
              scheme: HTTP
              port: {{ .Values.openpolicyagent.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: openpolicyagent-v2
              mountPath: /opt/vnc-proxy/rego/v2
              readOnly: true
        {{- end }}
        - name: vncproxy
          securityContext:
            {{- toYaml .Values.armSecurityContext | nindent 12 }}
          image: {{ include "vnc-proxy.imagename" . | quote }}
          imagePullPolicy: {{ .Values.vncProxy.image.pullPolicy }}
          command: [ "/usr/local/bin/vnc-proxy" ]
          env:
            - name: MSG_SIZE_LIMIT
              value: {{ .Values.serviceArgs.msgSizeLimit | quote }}
            - name: RATE_LIMITER_QPS
              value: {{ .Values.config.rateLimiter.qps | quote }}
            - name: RATE_LIMITER_BURST
              value: {{ .Values.config.rateLimiter.burst | quote }}
            - name: LOGGING_CONFIG
              value: /opt/vnc-proxy/logging.yaml
            - name: OIDC_SERVER_URL
              value: {{ .Values.openidc.issuer }}
            - name: OPA_PORT
              value: "{{ .Values.openpolicyagent.port }}"
            - name: OIDC_TLS_INSECURE_SKIP_VERIFY
              value: {{ .Values.openidc.insecureSkipVerify | quote }}
            - name: USE_M2M_TOKEN
              value: {{  .Values.useM2MToken | quote }}
            - name: VAULT_SERVER
              value: {{ .Values.vaultServer | quote }}
            - name: KEYCLOAK_SERVER
              value: {{ .Values.keycloakServer | quote }}
            - name: SERVICE_ACCOUNT
              value: {{  .Values.serviceAccount.name | quote }}
            {{- if .Values.openpolicyagent.enabled }}
            - name: OPA_ENABLED
              value: "true"
            {{- end}}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.webSocketServer.port}}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.webSocketServer.port}}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.vncProxyResources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/vnc-proxy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "app-resource-manager.fullname" . }}
        {{- if .Values.openpolicyagent.enabled }}
        - name: openpolicyagent-v2
          configMap:
            name: {{ include "app-resource-manager.fullname" . }}-opa-rego-v2
        {{- end }}
