# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = ["venv_/**", "out/*", "**go.sum", ".tool-versions", "**.json", "VERSION", "artifacts/**",
        "artifacts/**", "internal/**/mocks/**", ".htmllintrc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
