# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
version: "2"
run:
  build-tags:
    - codeanalysis
linters:
  disable:
    - staticcheck
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Error return value of `.*Close` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Flush` is not checked
    paths:
      - internal/skupper
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - internal/skupper
      - third_party$
      - builtin$
      - examples$
