# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = [
    "VERSION", "go.sum", "build/_output/**", "internal/skupper/**", "artifacts/**",
    "config/**", "deploy/charts/app-interconnect-manager/crds/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
