{
 "title": "App Resource Manager Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "Prometheus" }
  ]
 },
 "panels": [
  {
   "title": "App Resource Manager CPU usage Per POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=~\"app-resource-manager.+\",container!=\"\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "App Resource Manager Memory usage Per POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"app-resource-manager.+\",container!=\"\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "App Resource Manager Network Bytes Per POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "tx-{{pod}}"
    },
    {
     "expr": "container_network_receive_bytes_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "rx-{{pod}}"
    }
   ]
  },
  {
   "title": "App Resource Manager Network Packets Per POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "container_network_transmit_packets_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "tx-{{pod}}"
    },
    {
     "expr": "container_network_receive_packets_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "rx-{{pod}}"
    }
   ]
  },
  {
   "title": "App Resource Manager Network Packet Dropped Per POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "container_network_transmit_packets_dropped_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "tx-{{pod}}"
    },
    {
     "expr": "container_network_receive_packets_dropped_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "rx-{{pod}}"
    }
   ]
  },
  {
   "title": "App Resource Manager Network Errors Per POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "container_network_transmit_errors_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "tx-{{pod}}"
    },
    {
     "expr": "container_network_receive_errors_total{pod=~\"app-resource-manager.+\"}",
     "legendFormat": "rx-{{pod}}"
    }
   ]
  }
 ]
}