// SPDX-FileCopyrightText: (C) 2024 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/open-edge-platform/app-orch-deployment/app-interconnect/pkg/apis/network/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkServices implements NetworkServiceInterface
type FakeNetworkServices struct {
	Fake *FakeNetworkV1alpha1
}

var networkservicesResource = v1alpha1.SchemeGroupVersion.WithResource("networkservices")

var networkservicesKind = v1alpha1.SchemeGroupVersion.WithKind("NetworkService")

// Get takes name of the networkService, and returns the corresponding networkService object, and an error if there is any.
func (c *FakeNetworkServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networkservicesResource, name), &v1alpha1.NetworkService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkService), err
}

// List takes label and field selectors, and returns the list of NetworkServices that match those selectors.
func (c *FakeNetworkServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networkservicesResource, networkservicesKind, opts), &v1alpha1.NetworkServiceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkServiceList{ListMeta: obj.(*v1alpha1.NetworkServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkServices.
func (c *FakeNetworkServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networkservicesResource, opts))
}

// Create takes the representation of a networkService and creates it.  Returns the server's representation of the networkService, and an error, if there is any.
func (c *FakeNetworkServices) Create(ctx context.Context, networkService *v1alpha1.NetworkService, opts v1.CreateOptions) (result *v1alpha1.NetworkService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networkservicesResource, networkService), &v1alpha1.NetworkService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkService), err
}

// Update takes the representation of a networkService and updates it. Returns the server's representation of the networkService, and an error, if there is any.
func (c *FakeNetworkServices) Update(ctx context.Context, networkService *v1alpha1.NetworkService, opts v1.UpdateOptions) (result *v1alpha1.NetworkService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networkservicesResource, networkService), &v1alpha1.NetworkService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkServices) UpdateStatus(ctx context.Context, networkService *v1alpha1.NetworkService, opts v1.UpdateOptions) (*v1alpha1.NetworkService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(networkservicesResource, "status", networkService), &v1alpha1.NetworkService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkService), err
}

// Delete takes name of the networkService and deletes it. Returns an error if one occurs.
func (c *FakeNetworkServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(networkservicesResource, name, opts), &v1alpha1.NetworkService{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networkservicesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkServiceList{})
	return err
}

// Patch applies the patch and returns the patched networkService.
func (c *FakeNetworkServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkservicesResource, name, pt, data, subresources...), &v1alpha1.NetworkService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkService), err
}
