# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "interconnect-manager.fullname" . }}
  labels:
    {{ include "interconnect-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "interconnect-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "interconnect-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
