# yamllint disable-file
  # SPDX-FileCopyrightText: (C) 2024 Intel Corporation
  #
  # SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "interconnect-manager.fullname" . }}
  labels:
    {{- include "interconnect-manager.labels" . | nindent 4 }}
data:
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}
