# yamllint disable-file
  # SPDX-FileCopyrightText: (C) 2024 Intel Corporation
  #
  # SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.interconnect_manager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "interconnect-manager.serviceAccountName" . }}
  labels:
    {{- include "interconnect-manager.labels" . | nindent 4 }}
{{- end }}