{
 "title": "App Orch Scale",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Deployment Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status)(adm_deployment_status{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DeploymentCluster Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status)(adm_deployment_cluster_status{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-namespace CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (k8s_pod_cpu_utilization)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-namespace Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (k8s_pod_memory_usage)",
     "legendFormat": "{{k8s_namespace_name}}"
    }
   ]
  }
 ]
}