# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.adm.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app-deployment-manager.labels" . | nindent 4 }}
  name: {{ template "app-deployment-manager.name" . }}-metrics
spec:
  ports:
    - name: http-metrics
      port: {{ .Values.adm.metrics.port }}
      protocol: TCP
      targetPort: http-metrics
  selector:
    {{- include "app-deployment-manager.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app-deployment-manager.labels" . | nindent 4 }}
  name: {{ template "app-deployment-manager.name" . }}-status
spec:
  ports:
    - name: http-status
      port: {{ .Values.adm.metrics.port }}
      protocol: TCP
      targetPort: http-metrics
  selector:
    {{- include "app-deployment-manager.labels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "app-deployment-manager.labels" . | nindent 4 }}
  name: {{ template "app-deployment-manager.name" . }}
spec:
  endpoints:
  - port: http-metrics
    scheme: http
    path: /metrics
  - port: http-status
    scheme: http
    path: /status
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: NotIn
      values:
      - "false"
    matchLabels:
      {{- include "app-deployment-manager.labels" . | nindent 6 }}
---
{{- if .Values.gateway.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app-deployment-manager-api.labels" . | nindent 4 }}
  name: {{ template "app-deployment-manager-api.name" . }}-api-metrics
spec:
  ports:
    - name: http-metrics
      port: {{ .Values.gateway.metrics.port }}
      protocol: TCP
      targetPort: http-metrics
  selector:
    {{- include "app-deployment-manager-api.labels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "app-deployment-manager-api.labels" . | nindent 4 }}
  name: {{ template "app-deployment-manager-api.name" . }}
spec:
  endpoints:
  - port: http-metrics
    scheme: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchExpressions:
    - key: prometheus.io/service-monitor
      operator: NotIn
      values:
      - "false"
    matchLabels:
      {{- include "app-deployment-manager.labels" . | nindent 6 }}
      {{- include "app-deployment-manager-api.labels" . | nindent 6 }}
{{- end }}
{{- end }}
