# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.adm.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app-deployment-manager.serviceAccountName" . }}
  labels:
    {{- include "app-deployment-manager.labels" . | nindent 4 }}
{{- end }}
