# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.gateway.service.name }}-grpc-server"
spec:
  type: {{ .Values.gateway.service.grpcServer.type }}
  selector:
    app: "{{ .Values.gateway.deployment.name }}"
  ports:
    - protocol: TCP
      name: grpc
      port: {{ .Values.gateway.service.grpcServer.port }}
      targetPort: {{ .Values.gateway.service.grpcServer.targetPort }} # container port
    {{- if eq .Values.gateway.service.grpcServer.type "NodePort" }}
      nodePort: {{ .Values.gateway.service.grpcServer.nodePort }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.gateway.service.name }}-rest-proxy"
spec:
  type: {{ .Values.gateway.service.restProxy.type }}
  selector:
    app: "{{ .Values.gateway.deployment.name }}"
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.gateway.service.restProxy.port }}
      targetPort: {{ .Values.gateway.service.restProxy.targetPort }} # container port
---
{{- if .Values.openpolicyagent.enabled -}}
{{- if .Values.gateway.service.opa.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.service.name }}-opa
  labels:
    {{- include "app-deployment-manager-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.opa.type }}
  ports:
    - port: {{ .Values.gateway.service.opa.port }}
      targetPort: {{ .Values.gateway.service.opa.port }}
      protocol: TCP
      name: http-opa
  selector:
    {{- include "app-deployment-manager-api.selectorLabels" . | nindent 4 }}
{{- end}}
{{- end}}
