# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: webhook-service
  name: webhook-service
spec:
  ports:
  - name: tcp-webhook
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: {{ template "app-deployment-manager.name" . }}