---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: ADM Component Tests
on:
  pull_request:
    types: [labeled]
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch:  # Run on manual trigger
    inputs:
      run-adm:
        description: 'Run App Deployment Manager component tests'
        required: true
        type: boolean
        default: false
      emf-branch:
        description: 'The branch, tag or SHA to checkout EMF'
        required: true
        type: string
        default: '39c68d470051ab5e3ade750ebb11044718d76e10'
permissions:
  contents: read


jobs:
  component-test-adm:
    if: ${{ inputs.run-adm || github.event_name == 'schedule' || github.event.label.name == 'run-adm-component-tests' }}
    name: ADM Component Test
    uses: ./.github/workflows/common-comp-tests.yml
    with:
      component: app-deployment-manager
      use-enic: true
      emf-branch: ${{ inputs.emf-branch || '39c68d470051ab5e3ade750ebb11044718d76e10' }}
    secrets: inherit
