---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Component Tests
on:
  pull_request:
    branches:
      - main
      - release-*
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch:  # Run on manual trigger
    inputs:
      run-adm:
        description: 'Run App Deployment Manager component tests'
        required: true
        type: boolean
        default: false
      run-arm:
        description: 'Run App Resource Manager component tests'
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  component-test-adm:
    # if: ${{ inputs.run-adm || github.event_name == 'schedule' || github.event.label.name == 'run-adm-component-tests' }}
    name: Deploy Kind Orchestrator and Run ADM Component Tests
    timeout-minutes: 60
    uses: ./.github/workflows/component-tests.yml
    with:
      component: app-deployment-manager
      use-enic: false # todo: set to true after testing
      EMF_BRANCH: main
    secrets: inherit
